import { lessons } from './data.js';

const storage = { get: (key, fallback) => { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } }, set: (key, value) => localStorage.setItem(key, JSON.stringify(value)) };
const state = { lessonId: '', translations: storage.get('yk-translations', true), dark: storage.get('yk-dark', false), mastered: storage.get('yk-mastered', []), completed: storage.get('yk-completed', []), speaking: null, voiceWarning: false };
let koreanVoices = [];
const synthesis = window.speechSynthesis;
function updateVoices() { koreanVoices = synthesis ? synthesis.getVoices().filter((voice) => /^ko([_-]|$)/i.test(voice.lang)) : []; state.voiceWarning = !synthesis || koreanVoices.length === 0; render(); }
if (synthesis) { synthesis.addEventListener?.('voiceschanged', updateVoices); setTimeout(updateVoices, 120); } else state.voiceWarning = true;
function stopSpeaking() { if (synthesis) synthesis.cancel(); state.speaking = null; }
function speak(text, id) { if (!synthesis) { state.voiceWarning = true; render(); return; } if (state.speaking === id) { stopSpeaking(); render(); return; } stopSpeaking(); const utterance = new SpeechSynthesisUtterance(text); utterance.lang = 'ko-KR'; if (koreanVoices[0]) utterance.voice = koreanVoices[0]; utterance.onend = utterance.onerror = () => { if (state.speaking === id) { state.speaking = null; render(); } }; state.speaking = id; synthesis.speak(utterance); render(); }
function toggle(list, value, key) { const next = list.includes(value) ? list.filter((v) => v !== value) : [...list, value]; state[key] = next; storage.set(`yk-${key}`, next); render(); }
function korean(text, id) { const active = state.speaking === id; return `<span class="korean-text" lang="ko">${text}</span><button class="speak ${active ? 'active' : ''}" data-speak="${id}" data-text="${encodeURIComponent(text)}" aria-label="朗读：${text}">${active ? '⏹ 停止' : '🔊 朗读'}</button>`; }
function translation(text) { return state.translations ? `<p class="translation">${text}</p>` : ''; }
function vocabulary(items, lessonId, compact = false) { if (!items.length) return '<p class="empty">等待添加词汇。请编辑 <code>src/data.js</code> 中对应课程。</p>'; return `<div class="vocab-list ${compact ? 'compact' : ''}">${items.map((item) => { const mastered = state.mastered.includes(item.id); return `<article class="word"><div><strong>${korean(item.korean, `word-${item.id}`)}</strong><span class="pos">${item.partOfSpeech || ''}</span>${translation(item.meaning)}</div><button class="mastered ${mastered ? 'done' : ''}" data-mastered="${item.id}" aria-pressed="${mastered}">${mastered ? '✓ 已掌握' : '标记掌握'}</button></article>`; }).join('')}</div>`; }
function sectionHtml(section, lesson) { const grammar = section.grammar.length ? section.grammar.map((point, p) => `<article class="inner-card"><h4>📖 语法 · <span lang="ko">${point.pattern}</span></h4>${translation(point.explanation)}<p class="tip">用法提示：${point.tips}</p><ol class="examples">${point.examples.map((e, i) => `<li>${korean(e.korean, `${section.id}-g${p}-${i}`)}${translation(e.translation)}</li>`).join('')}</ol></article>`).join('') : '<p class="empty">暂无语法内容；这是可编辑的课程占位区。</p>';
 const dialogues = section.dialogues.length ? `<div class="dialogues">${section.dialogues.map((line, i) => `<div class="dialogue"><b>${line.speaker}</b><div>${korean(line.korean, `${section.id}-d${i}`)}${translation(line.translation)}</div></div>`).join('')}</div>` : '<p class="empty">暂无课文内容；可在数据文件中添加逐句对话。</p>';
 return `<section class="section-card"><div class="section-heading"><span>${section.order}</span><div><h3 lang="ko">${section.koreanTitle}</h3><p>${section.chineseTitle}</p></div></div><p class="objective"><b>学习目标：</b>${section.objective}</p><div class="content-grid"><div><h4>📖 语法</h4>${grammar}</div><div><h4>💬 课文</h4>${dialogues}</div></div><h4>📝 本小节重点单词</h4>${vocabulary(section.vocabulary, lesson.id, true)}</section>`; }
function render() { const lesson = lessons.find((item) => item.id === state.lessonId) || lessons[0]; state.lessonId = lesson.id; document.documentElement.dataset.theme = state.dark ? 'dark' : 'light'; const complete = state.completed.includes(lesson.id); const filtered = lesson.allVocabulary.filter((item) => { const q = document.querySelector('#search')?.value?.trim().toLowerCase() || ''; const masteredOnly = document.querySelector('#mastered-only')?.checked; return (!q || item.korean.includes(q) || item.meaning.toLowerCase().includes(q)) && (!masteredOnly || state.mastered.includes(item.id)); });
 document.querySelector('#app').innerHTML = `<header class="top"><div class="brand"><span class="logo" aria-hidden="true">가</span><div><h1>延世韩国语 第一册 · 我的学习手册</h1><p>第 1–10 课 · 点击 🔊 即可听韩语发音</p></div></div><div class="toolbar"><button id="translate" aria-pressed="${state.translations}">${state.translations ? '隐藏中文翻译' : '显示中文翻译'}</button><button id="theme" aria-pressed="${state.dark}">${state.dark ? '☀️ 浅色' : '🌙 深色'}</button></div></header>${state.voiceWarning ? '<p class="voice-warning" role="status">当前浏览器未检测到韩语语音，可在系统语音设置中安装韩语语音后重试。</p>' : ''}<main><nav aria-label="课程导航" class="lesson-nav">${lessons.map((item) => `<a href="#${item.id}" class="${item.id === lesson.id ? 'current' : ''}" aria-current="${item.id === lesson.id ? 'page' : 'false'}"><b>${item.number}</b><span>第${item.number}课<br/>${item.chineseName}</span></a>`).join('')}</nav><div class="progress"><span>已完成 ${state.completed.length} / 10 课</span><div aria-label="总体学习进度"><i style="width:${state.completed.length * 10}%"></i></div></div><article class="lesson"><div class="lesson-intro"><div><p class="eyebrow">第 ${lesson.number} 课 · <span lang="ko">${lesson.koreanTopic}</span></p><h2>${lesson.chineseName}</h2><p>以下为个人学习示范与可扩展结构，并不声称逐字对应教材。</p><button class="complete ${complete ? 'done' : ''}" data-complete="${lesson.id}" aria-pressed="${complete}">${complete ? '✓ 本课已完成' : '标记本课完成'}</button></div><figure><img src="${lesson.illustration}" alt="${lesson.chineseName}课程的待替换插画" loading="lazy" width="360" height="240" /></figure></div>${lesson.sections.map((s) => sectionHtml(s, lesson)).join('')}<section class="section-card overview"><h3>本课词汇总览</h3><div class="filters"><label>搜索词汇 <input id="search" type="search" placeholder="韩语或中文" aria-label="搜索本课词汇" /></label><label><input id="mastered-only" type="checkbox" /> 仅看已掌握</label></div>${vocabulary(filtered, lesson.id)}</section></article></main><footer>插画素材：<a href="https://www.irasutoya.com/" target="_blank" rel="noreferrer">いらすとや（Irasutoya）</a>｜仅作个人学习网站的页面装饰使用 <span>（当前为本地 TODO 占位插画，替换前请确认官方来源与使用条款。）</span></footer>`;
 document.querySelectorAll('[data-speak]').forEach((button) => button.addEventListener('click', () => speak(decodeURIComponent(button.dataset.text), button.dataset.speak))); document.querySelectorAll('[data-mastered]').forEach((button) => button.addEventListener('click', () => toggle(state.mastered, button.dataset.mastered, 'mastered'))); document.querySelector('[data-complete]')?.addEventListener('click', (e) => toggle(state.completed, e.currentTarget.dataset.complete, 'completed')); document.querySelector('#translate').onclick = () => { state.translations = !state.translations; storage.set('yk-translations', state.translations); render(); }; document.querySelector('#theme').onclick = () => { state.dark = !state.dark; storage.set('yk-dark', state.dark); render(); }; document.querySelector('#search').addEventListener('input', render); document.querySelector('#mastered-only').addEventListener('change', render); }
function changeLesson() { stopSpeaking(); state.lessonId = location.hash.slice(1) || lessons[0].id; render(); }
window.addEventListener('hashchange', changeLesson); window.addEventListener('beforeunload', stopSpeaking); changeLesson();
